# Generated by Django 5.2 on 2025-12-26 14:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile/about/', verbose_name='Image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='About', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'About Section',
                'verbose_name_plural': 'About Sections',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Job Title')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Bio')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='profile/avatars/', verbose_name='Avatar')),
                ('cv_file', models.FileField(blank=True, null=True, upload_to='profile/files/', verbose_name='Resumé CV')),
                ('github_url', models.URLField(blank=True, null=True, verbose_name='GitHub')),
                ('linkedin_url', models.URLField(blank=True, null=True, verbose_name='LinkedIn')),
                ('youtube_url', models.URLField(blank=True, null=True, verbose_name='Youtube')),
                ('facebook_url', models.URLField(blank=True, null=True, verbose_name='Facebook')),
                ('instagram_url', models.URLField(blank=True, null=True, verbose_name='Instagram')),
                ('whatsapp_url', models.URLField(blank=True, null=True, verbose_name='Whatsapp')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
    ]
