# Generated by Django 5.2 on 2025-12-26 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Published'),
        ),
    ]
