# Generated by Django 5.2 on 2025-12-26 14:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hero', models.BooleanField(default=True)),
                ('about', models.BooleanField(default=True)),
                ('about_title', models.CharField(max_length=255)),
                ('about_description', models.TextField(blank=True, null=True)),
                ('skills', models.BooleanField(default=True)),
                ('skill_title', models.CharField(max_length=255)),
                ('skill_description', models.TextField(blank=True, null=True)),
                ('project', models.BooleanField(default=True)),
                ('project_title', models.CharField(max_length=255)),
                ('project_description', models.TextField(blank=True, null=True)),
                ('experience', models.BooleanField(default=True)),
                ('experience_title', models.CharField(max_length=255)),
                ('experience_description', models.TextField(blank=True, null=True)),
                ('education', models.BooleanField(default=True)),
                ('education_title', models.CharField(max_length=255)),
                ('education_description', models.TextField(blank=True, null=True)),
                ('certificate', models.BooleanField(default=True)),
                ('certificate_title', models.CharField(max_length=255)),
                ('certificate_description', models.TextField(blank=True, null=True)),
                ('service', models.BooleanField(default=True)),
                ('service_title', models.CharField(max_length=255)),
                ('service_description', models.TextField(blank=True, null=True)),
                ('contact', models.BooleanField(default=True)),
                ('contact_title', models.CharField(max_length=255)),
                ('contact_description', models.TextField(blank=True, null=True)),
                ('faq', models.BooleanField(default=True)),
                ('faq_title', models.CharField(max_length=255)),
                ('faq_description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Content',
                'verbose_name_plural': 'Contents',
            },
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Faq',
                'verbose_name_plural': 'Faqs',
            },
        ),
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('dark_logo', models.ImageField(blank=True, null=True, upload_to='settings/platform/', verbose_name='Dark Logo')),
                ('light_logo', models.ImageField(blank=True, null=True, upload_to='settings/platform/', verbose_name='Light Logo')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='settings/platform/')),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Contact Email')),
                ('support_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Support Email')),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Platform Settings',
                'verbose_name_plural': 'Platform Settings',
            },
        ),
    ]
